org: "drycc"
pull_policy: "Always"
docker_tag: canary
versions_api_url: https://versions-staging.drycc.com
doctor_api_url: https://doctor-staging.drycc.com
# limits_cpu: "100m"
# limits_memory: "50Mi"
