apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: drycc-workflow-manager
  labels:
    heritage: drycc
  annotations:
    component.drycc.cc/version: {{ .Values.docker_tag }}
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: drycc-workflow-manager
  template:
    metadata:
      labels:
        app: drycc-workflow-manager
    spec:
      serviceAccount: drycc-workflow-manager
      containers:
      - name: drycc-workflow-manager
        image: {{.Values.docker_registry}}{{.Values.org}}/workflow-manager:{{.Values.docker_tag}}
        imagePullPolicy: {{.Values.pull_policy}}
{{- if or (.Values.limits_cpu) (.Values.limits_memory)}}
        resources:
          limits:
{{- if (.Values.limits_cpu) }}
            cpu: {{.Values.limits_cpu}}
{{- end}}
{{- if (.Values.limits_memory) }}
            memory: {{.Values.limits_memory}}
{{- end}}
{{- end}}
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: PORT
          value: "8080"
        - name: VERSIONS_API_URL
          value: {{.Values.versions_api_url}}
        - name: DOCTOR_API_URL
          value: {{.Values.doctor_api_url}}
        - name: POLL_INTERVAL_SEC
          value: "43200"
        - name: CHECK_VERSIONS
          value: "true"
        - name: API_VERSION
          value: "v2"
        - name: DRYCC_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - containerPort: 8080
