apiVersion: v1
kind: Service
metadata:
  name: drycc-workflow-manager
  labels:
    heritage: drycc
    router.drycc.cc/routable: "true"
  annotations:
    router.drycc.cc/domains: drycc-workflow-manager
spec:
  selector:
    app: drycc-workflow-manager
  ports:
    - name: http
      port: 80
      targetPort: 8080
