{{- if (.Values.global.use_rbac) -}}
{{- if (.Capabilities.APIVersions.Has (include "rbacAPIVersion" .)) -}}
kind: ClusterRole
apiVersion: {{ template "rbacAPIVersion" . }}
metadata:
  name: drycc:drycc-workflow-manager
  labels:
    app: drycc-workflow-manager
    heritage: drycc
rules:
- apiGroups: ["extensions", "apps"]
  resources: ["deployments", "daemonsets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["namespaces", "replicationcontrollers"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "delete", "update"]
{{- end -}}
{{- end -}}
